baseurl = "https://sdorsett.github.io"
languageCode = "en-us"
title = "Things I find interesting"
theme = "blackburn"
author = "Stan Dorsett"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Automating all the things"
  brand = " "
  #googleAnalytics = "Your Google Analytics tracking ID"
  #disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topics"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 5
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "Favorites"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 6
    identifier = "links"
    url = "https://github.com/sdorsett/interesting-links"
[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "standorsett"
  github = "sdorsett"
  linkedin = "stan-dorsett-53a8827"
